name: simple_drawer
description: simple_drawer offers an easy way to implement your own widget as a drawer which slides in from any direction (top, bottom, left & right).
version: 0.0.10
homepage: https://github.com/DavidKlant/simple_drawer

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


